### ISSUE TITLE
Checking postconditions on a SUT-returning function does not work

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml-gospel/ortac#258]
Ortac version: 0753c72

Reproducer:

`int31.mli`:
```ocaml
type t
(*@ model i : integer *)

val of_int : int -> t
(*@ x = of_int j
    ensures x.i = 0xdeadbeef
 *)
```

`int31.ml`:
```ocaml
type t = int31

let of_int = Int32.of_int (* clearly wrong *)
```

`ortac_conf.ml`:
```ocaml
open Int31lib.Int31
type sut = t
let init_sut = of_int 42

module Pp = struct
  include Util.Pp

  let pp_t b fmt t = Util.Pp.pp_string b fmt (show t)
end

module Gen = struct
  include QCheck.Gen

  let int31_corners = [-(1 lsl 30); 1 lsl 30 - 1]

  (* Not small neither signed... working around a limitation of Ortac here: it
     always uses Gen.small_signed_int as an int generator. *)
  let small_signed_int = graft_corners int int31_corners ()
end

module Ty = struct
  type _ ty += T : t ty

  let t =
    (T, show)
end
```

All tests pass, although the postcondition should clearly be false most of the time.

**Comment by n-osborne** [comment]
The post-condition of `of_int` is indeed not checked as it is used to generate the `next_state` function for QCheck-STM.

The idea is that the discrepancy between the actual value and the model of the sut will be caught later in the generated (STM) program.

Let's say you add a `is_deadbeef` predicate to your module with the expected behaviour *wrt* the name and the correct gospel specifications.
When running the predicate in the generated list of commands, the model will say `true` when the actual function will most likely return `false`.

**Comment by OlivierNicole** [comment]
Oh, so that’s how it works, I see. Thanks for the explanation!
